
export enum PlaceType {
    AMUSEMENT_PARK = "amusement_park",
    AQUARIUM = "aquarium",
    ART_GALLERY = "art_gallery",
    BAKERY = "bakery",
    BAR = "bar",
    BEAUTY_SALON = "beauty_salon",
    BOOK_STORE = "book_store",
    BOWLING_ALLEY = "bowling_alley",
    CAFE = "cafe",
    CAMPGROUND = "campground",
    CASINO = "casino",
    CHURCH = "church",
    CITY_HALL = "city_hall",
    GYM = "gym",
    HAIR_CARE = "hair_care",
    HINDU_TEMPLE = "hindu_temple",
    MEAL_DELIVERY = "meal_delivery",
    MEAL_TAKEAWAY = "meal_takeaway",
    MOSQUE = "mosque",
    MOVIE_RENTAL = "movie_rental",
    MOVIE_THEATER = "movie_theater",
    MUSEUM = "museum",
    NIGHT_CLUB = "night_club",
    PARK = "park",
    RESTAURANT = "restaurant",
    SHOPPING_MALL = "shopping_mall",
    SPA = "spa",
    STADIUM = "stadium",
    SYNAGOGUE = "synagogue",
    TOURIST_ATTRACTION = "tourist_attraction",
    ZOO = "zoo"
  }
  